version: "3.9"
    
services:
  frontend:
    build: .
    container_name: frontend-poc      
    environment:
      NODE_ENV: development
    ports:        
      - 3000:3000
    networks:
      - network-name
  
networks:
  network-name:
    name: poc
      